# Generated by Django 5.1.7 on 2025-05-13 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Full Name")),
                ("email", models.EmailField(max_length=40, verbose_name="Email")),
                ("contents", models.TextField(max_length=400, verbose_name="Message")),
                (
                    "number",
                    models.CharField(max_length=13, verbose_name="Phone Number"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Submission Time",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Read Status"),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contact List",
                "ordering": ["-created_at"],
            },
        ),
    ]
